
//
//  LocalizedKey.h
//  Hunt
//
//  Created by 杨明 on 2018/8/17.
//  Copyright © 2018年 congzhi. All rights reserved.
//

#ifndef LocalizedKey_h
#define LocalizedKey_h

//tab
#define Market LocalizedString(@"Market")
#define Me LocalizedString(@"Me")
#define College LocalizedString(@"College")
#define Candy LocalizedString(@"Candy")
#define Application LocalizedString(@"Application")

//college
#define CourseIntroduce LocalizedString(@"CourseIntroduce")
#define IntroToCollege LocalizedString(@"IntroToCollege")
#define Directory LocalizedString(@"Directory")
#define JoinStudy LocalizedString(@"JoinStudy")
#define ImmediatePayment LocalizedString(@"ImmediatePayment")
#define EarnCandy LocalizedString(@"EarnCandy")
#define Free LocalizedString(@"Free")
#define Period LocalizedString(@"Period")
#define StudyOfPeople LocalizedString(@"StudyOfPeople")
#define SalePrice LocalizedString(@"SalePrice")
#define OriPrice LocalizedString(@"OriPrice")
#define TryIt LocalizedString(@"TryIt")
#define ShouldPay LocalizedString(@"ShouldPay")
#define ConfirmOrder LocalizedString(@"ConfirmOrder")
#define RainbowCollege LocalizedString(@"RainbowCollege")
#define PosterCodeTag LocalizedString(@"PosterCodeTag")
#define PleaseJoinBundle LocalizedString(@"PleaseJoinBundle")
#define BuySuccessAlert LocalizedString(@"BuySuccessAlert")
#define LearnNow LocalizedString(@"LearnNow")



//markets
#define Markets LocalizedString(@"Markets")
#define Exchange LocalizedString(@"Exchange")
#define Optional LocalizedString(@"Optional")
#define MarketValueGain LocalizedString(@"MarketValueGain")
#define MarketCap LocalizedString(@"MarketCap")
#define Volume LocalizedString(@"Volume")
#define Price LocalizedString(@"Price")
#define Change LocalizedString(@"Change")
#define AddEditOptions LocalizedString(@"AddEditOptions")
#define IntelligentRecommendation LocalizedString(@"IntelligentRecommendation")
#define ClickToAdd LocalizedString(@"ClickToAdd")
#define ChangeReload LocalizedString(@"ChangeReload")
#define NotReallyInterestedAddMyself LocalizedString(@"NotReallyInterestedAddMyself")
#define Name LocalizedString(@"Name")
#define DayTurnover LocalizedString(@"DayTurnover")
#define HighDay LocalizedString(@"HighDay")
#define TotalDay LocalizedString(@"TotalDay")
#define CirculationValue LocalizedString(@"CirculationValue")
#define LowDay LocalizedString(@"LowDay")
#define ChangeDay LocalizedString(@"ChangeDay")
#define MarketRank LocalizedString(@"MarketRank")
#define Today LocalizedString(@"Today")
#define Money LocalizedString(@"Money")
#define Introduce LocalizedString(@"Introduce")
#define Close LocalizedString(@"Close")
#define TimeSharing LocalizedString(@"TimeSharing")
#define TimeShort LocalizedString(@"TimeShort")
#define KLine LocalizedString(@"KLine")
#define TKL LocalizedString(@"TKL")
#define DZKL LocalizedString(@"DZKL")
#define QKKL LocalizedString(@"QKKL")
#define All LocalizedString(@"All")
#define DayK LocalizedString(@"DayK")
#define WeekK LocalizedString(@"WeekK")
#define MonthK LocalizedString(@"MonthK")
#define AddOptional LocalizedString(@"AddOptional")
#define KeyAdd LocalizedString(@"KeyAdd")
#define PackUp LocalizedString(@"PackUp")
#define Unfold LocalizedString(@"Unfold")
#define PopularCurrency LocalizedString(@"PopularCurrency")
#define CollectionAlertSummary LocalizedString(@"CollectionAlertSummary")
#define ShareAlertSummary LocalizedString(@"ShareAlertSummary")
#define ColAlertSummary LocalizedString(@"ColAlertSummary")
#define Add LocalizedString(@"Add")
#define ClickStarCancelCollect LocalizedString(@"ClickStarCancelCollect")
#define Drag LocalizedString(@"Drag")
#define Topping LocalizedString(@"Topping")
#define AddCollectSuccess LocalizedString(@"AddCollectSuccess")
#define RemoveCollectSuccess LocalizedString(@"RemoveCollectSuccess")
#define EditCollection LocalizedString(@"EditCollection")
#define CirculatingSupply LocalizedString(@"CirculatingSupply")
#define MaxSupply LocalizedString(@"MaxSupply")
#define CirculationRate LocalizedString(@"CirculationRate")
#define MaximumAmount LocalizedString(@"MaximumAmount")
#define CirculatingCap LocalizedString(@"CirculatingCap")
#define MarketCapRank LocalizedString(@"MarketCapRank")
#define TotalMarketCap LocalizedString(@"TotalMarketCap")
#define ProjectIntroduce LocalizedString(@"ProjectIntroduce")
#define NoCoinKline LocalizedString(@"NoCoinKline")
#define NoOpenStayTuned LocalizedString(@"NoOpenStayTuned")
#define Advertising LocalizedString(@"Advertising")
#define CirculatingSupplyInfoTag LocalizedString(@"CirculatingSupplyInfoTag")
#define TotalSupplyInfoTag LocalizedString(@"TotalSupplyInfoTag")
#define MaxSupplyInfoTag LocalizedString(@"MaxSupplyInfoTag")


//search
#define Search LocalizedString(@"Search")
#define InputCoinOrExchange LocalizedString(@"InputCoinOrExchange")
#define HistorySearch LocalizedString(@"HistorySearch")
#define HotSearch LocalizedString(@"HotSearch")
#define HotExchanges LocalizedString(@"HotExchanges")
#define Clear LocalizedString(@"Clear")
#define NoSearchTag LocalizedString(@"NoSearchTag")

//candy
#define RuleOfActivity LocalizedString(@"RuleOfActivity")
#define CheckNow LocalizedString(@"CheckNow")
#define CheckEnergyLeaderboard LocalizedString(@"CheckEnergyLeaderboard")
#define EnergyRank LocalizedString(@"EnergyRank")
#define Energy LocalizedString(@"Energy")
#define Rank LocalizedString(@"Rank")
#define UserName LocalizedString(@"UserName")
#define EnergyValue LocalizedString(@"EnergyValue")
#define GrowEnergy LocalizedString(@"GrowEnergy")
#define Strategy LocalizedString(@"Strategy")
#define Activity LocalizedString(@"Activity")
#define InviteFriends LocalizedString(@"InviteFriends")
#define UpdateOn LocalizedString(@"UpdateOn")
#define CurrentEnergy LocalizedString(@"CurrentEnergy")
#define QuicklyEarnEnergyImproveSpeedDigging LocalizedString(@"QuicklyEarnEnergyImproveSpeedDigging")
#define MoreContributionsMoreEnergyFasterOreGrows LocalizedString(@"MoreContributionsMoreEnergyFasterOreGrows")
#define BasicTasks LocalizedString(@"BasicTasks")
#define AdvancedTasks LocalizedString(@"AdvancedTasks")
#define RegisterAccount LocalizedString(@"RegisterAccount")
#define BonusCandy LocalizedString(@"BonusCandy")
#define DailyLogin LocalizedString(@"DailyLogin")
#define GetEnergy LocalizedString(@"GetEnergy")
#define EnergyPerson LocalizedString(@"EnergyPerson")
#define BindWallet LocalizedString(@"BindWallet")
#define PositionGetEnergy LocalizedString(@"PositionGetEnergy")
#define BuyMill LocalizedString(@"BuyMill")
#define MillGetEnergy LocalizedString(@"MillGetEnergy")
#define GrowingEnergy LocalizedString(@"GrowingEnergy")
#define Rainbow LocalizedString(@"Rainbow")
#define CandyTotalTag LocalizedString(@"CandyTotalTag")
#define CandyIntroInfo LocalizedString(@"CandyIntroInfo")
#define IncomeExpenditureRecord LocalizedString(@"IncomeExpenditureRecord")
#define RedemptionNotOpen LocalizedString(@"RedemptionNotOpen")
#define CandyRecord LocalizedString(@"CandyRecord")
#define CurrenctEnergyValue LocalizedString(@"CurrenctEnergyValue")
#define EnergyIntroInfo LocalizedString(@"EnergyIntroInfo")
#define EnergyRecord LocalizedString(@"EnergyRecord")
#define SigninEnergyReward LocalizedString(@"SigninEnergyReward")
#define LoginToReceive LocalizedString(@"LoginToReceive")
#define RankedFirstTag LocalizedString(@"RankedFirstTag")
#define RankedLastTag LocalizedString(@"RankedLastTag")


//Application
#define BlockApplication LocalizedString(@"BlockApplication")
#define CheckMore LocalizedString(@"CheckMore")
#define Recommended LocalizedString(@"Recommended")
#define DownloadRank LocalizedString(@"DownloadRank")
#define Install LocalizedString(@"Install")
#define Installing LocalizedString(@"Installing")
#define Download LocalizedString(@"Download")
#define AppSearch LocalizedString(@"AppSearch")
#define InstallAtOnce LocalizedString(@"InstallAtOnce")
#define TimeNumber LocalizedString(@"TimeNumber")
#define TrustTutorial LocalizedString(@"TrustTutorial")
#define InstallPrompt LocalizedString(@"InstallPrompt")
#define GoTrust LocalizedString(@"GoTrust")
#define InstallPromptTag1 LocalizedString(@"InstallPromptTag1")
#define InstallPromptTag2 LocalizedString(@"InstallPromptTag2")
#define CheckTrustDetail LocalizedString(@"CheckTrustDetail")
#define InstallDialogPopTag LocalizedString(@"InstallDialogPopTag")


//mine
#define MyInvitationCode LocalizedString(@"MyInvitationCode")
#define GenerateInvitationCARDS LocalizedString(@"GenerateInvitationCARDS")
#define CurrencyAssets LocalizedString(@"CurrencyAssets")
#define MessageCenter LocalizedString(@"MessageCenter")
#define SwitchColorOfCandlestick LocalizedString(@"SwitchColorOfCandlestick")
#define CurrencySettings LocalizedString(@"CurrencySettings")
#define Language LocalizedString(@"Language")
#define SkinSwitch LocalizedString(@"SkinSwitch")
#define ContactUs LocalizedString(@"ContactUs")
#define AboutUs LocalizedString(@"AboutUs")
#define ClearCache LocalizedString(@"ClearCache")
#define InviteFriendsCarveUpCandy LocalizedString(@"InviteFriendsCarveUpCandy")
#define Avatar LocalizedString(@"Avatar")
#define NickName LocalizedString(@"NickName")
#define Mobile LocalizedString(@"Mobile")
#define EditPassword LocalizedString(@"EditPassword")
#define InputNickName LocalizedString(@"InputNickName")
#define EditNickName LocalizedString(@"EditNickName")
#define Save LocalizedString(@"Save")
#define InputOldPassword LocalizedString(@"InputOldPassword")
#define SetNewPassword LocalizedString(@"SetNewPassword")
#define SetNewPasswordAgain LocalizedString(@"SetNewPasswordAgain")
#define Done LocalizedString(@"Done")
#define ForgetPasswordFindByMobile LocalizedString(@"ForgetPasswordFindByMobile")
#define MobileFindPassword LocalizedString(@"MobileFindPassword")
#define MobileAreaCode LocalizedString(@"MobileAreaCode")
#define InputVerificationCode LocalizedString(@"InputVerificationCode")
#define GetVerificationCode LocalizedString(@"GetVerificationCode")
#define InputMobile LocalizedString(@"InputMobile")
#define InputPassword LocalizedString(@"InputPassword")
#define Retry LocalizedString(@"Retry")
#define SendVerificationCode LocalizedString(@"SendVerificationCode")
#define ChooseAvatarType LocalizedString(@"ChooseAvatarType")
#define TakePhoto LocalizedString(@"TakePhoto")
#define ChooseFromAlbum LocalizedString(@"ChooseFromAlbum")
#define Cancel LocalizedString(@"Cancel")
#define InviteCode LocalizedString(@"InviteCode")
#define Copy LocalizedString(@"Copy")
#define MyRecord LocalizedString(@"MyRecord")
#define RewardRules LocalizedString(@"RewardRules")
#define DigitalFutureControl LocalizedString(@"DigitalFutureControl")
#define InvitationCardEquippedSentFriends LocalizedString(@"InvitationCardEquippedSentFriends")
#define ShareMarketToFriends LocalizedString(@"ShareMarketToFriends")
#define ShareBundleToFriends LocalizedString(@"ShareBundleToFriends")
#define ShareNewsToFriends LocalizedString(@"ShareNewsToFriends")
#define ShareFlashToFriends LocalizedString(@"ShareFlashToFriends")
#define MakePoster LocalizedString(@"MakePoster")
#define WechatFriends LocalizedString(@"WechatFriends")
#define Moments LocalizedString(@"Moments")
#define ShareLink LocalizedString(@"ShareLink")
#define SaveLocal LocalizedString(@"SaveLocal")
#define System LocalizedString(@"System")
#define ElegantBlue LocalizedString(@"ElegantBlue")
#define VibrantOrange LocalizedString(@"VibrantOrange")
#define SimChineseLanguage LocalizedString(@"SimChineseLanguage")
#define EnglishLanguage LocalizedString(@"EnglishLanguage")
#define MineLoginTag LocalizedString(@"MineLoginTag")
#define Logout LocalizedString(@"Logout")
#define LogoutAlert LocalizedString(@"LogoutAlert")
#define Confirm LocalizedString(@"Confirm")
#define CurrencyShow LocalizedString(@"CurrencyShow")
#define CacheClearDone LocalizedString(@"CacheClearDone")
#define UserInfo LocalizedString(@"UserInfo")
#define UpdateTag LocalizedString(@"UpdateTag")
#define VersionTag LocalizedString(@"VersionTag")
#define UpdatesContent LocalizedString(@"UpdatesContent")
#define UpdateNow LocalizedString(@"UpdateNow")


//login
#define LoginSummary LocalizedString(@"LoginSummary")
#define Next LocalizedString(@"Next")
#define Login LocalizedString(@"Login")
#define CountryAndArea LocalizedString(@"CountryAndArea")
#define China LocalizedString(@"China")
#define LoginInviteSummary LocalizedString(@"LoginInviteSummary")

//alert
#define VerCodeSentSuccess LocalizedString(@"VerCodeSentSuccess")
#define PhoneNumberNotBlank LocalizedString(@"PhoneNumberNotBlank")
#define PleaseFillCorrectMobileNumber LocalizedString(@"PleaseFillCorrectMobileNumber")
#define VerCodeNotBlank LocalizedString(@"VerCodeNotBlank")
#define PleaseEnterCorrectVerCode LocalizedString(@"PleaseEnterCorrectVerCode")
#define RegisterSuccess LocalizedString(@"RegisterSuccess")
#define LoginSuccess LocalizedString(@"LoginSuccess")
#define EditSuccess LocalizedString(@"EditSuccess")
#define CurrentAccountNotLoggedIn LocalizedString(@"CurrentAccountNotLoggedIn")
#define NoDataTag LocalizedString(@"NoDataTag")
#define NewVersions LocalizedString(@"NewVersions")
#define UpdateTo LocalizedString(@"UpdateTo")
#define SaveSuccess LocalizedString(@"SaveSuccess")
#define ConfirmDelet LocalizedString(@"ConfirmDelet")
#define DelSuccess LocalizedString(@"DelSuccess")
#define CanNotExceed LocalizedString(@"CanNotExceed")
#define Character LocalizedString(@"Character")


//币资产
#define FromOptionalSelectCoin LocalizedString(@"FromOptionalSelectCoin")
#define ShowBalanceCurrency LocalizedString(@"ShowBalanceCurrency")
#define TotalAssets LocalizedString(@"TotalAssets")
#define Initials LocalizedString(@"Initials")
#define TodayGains LocalizedString(@"TodayGains")
#define CostRecord LocalizedString(@"CostRecord")
#define DefaultCurrencyGroup LocalizedString(@"DefaultCurrencyGroup")
#define CurrencyBuy LocalizedString(@"CurrencyBuy")
#define CurrencySale LocalizedString(@"CurrencySale")
#define AddCurrencyRecord LocalizedString(@"AddCurrencyRecord")
#define CurrencyInfo LocalizedString(@"CurrencyInfo")
#define StoreIn LocalizedString(@"StoreIn")
#define Remark LocalizedString(@"Remark")
#define ChooseCoin LocalizedString(@"ChooseCoin")
#define ChooseCurrency LocalizedString(@"ChooseCurrency")
#define Quantity LocalizedString(@"Quantity")
#define PleaseEnterQuantity LocalizedString(@"PleaseEnterQuantity")
#define BuyPricePerUnit LocalizedString(@"BuyPricePerUnit")
#define PleaseEnterBuyPrice LocalizedString(@"PleaseEnterBuyPrice")
#define SellPricePerUnit LocalizedString(@"SellPricePerUnit")
#define PleaseEnterSellPrice LocalizedString(@"PleaseEnterSellPrice")
#define Time LocalizedString(@"Time")
#define PleaseSelectTime LocalizedString(@"PleaseSelectTime")
#define Wallet LocalizedString(@"Wallet")
#define PickExchange LocalizedString(@"PickExchange")
#define PickOneExchange LocalizedString(@"PickOneExchange")
#define PleaseCopyWalletAdress LocalizedString(@"PleaseCopyWalletAdress")
#define PleaseChooseExchange LocalizedString(@"PleaseChooseExchange")
#define CurrencyForm LocalizedString(@"CurrencyForm")
#define Edit LocalizedString(@"Edit")
#define AddTransactionRecord LocalizedString(@"AddTransactionRecord")
#define MineCurrentAssets LocalizedString(@"MineCurrentAssets")
#define Choose LocalizedString(@"Choose")
#define PerUnit LocalizedString(@"PerUnit")
#define TotalUnit LocalizedString(@"TotalUnit")
#define TotalInvestment LocalizedString(@"TotalInvestment")
#define Profit LocalizedString(@"Profit")
#define NetCost LocalizedString(@"NetCost")
#define BuyAveragePrice LocalizedString(@"BuyAveragePrice")
#define SellAveragePrice LocalizedString(@"SellAveragePrice")
#define BuyUnitPrice LocalizedString(@"BuyUnitPrice")
#define TotalPurchase LocalizedString(@"TotalPurchase")
#define SaleUnitPrice LocalizedString(@"SaleUnitPrice")
#define SaleTotalPurchase LocalizedString(@"SaleTotalPurchase")
#define CurrentValue LocalizedString(@"CurrentValue")
#define Buy LocalizedString(@"Buy")
#define Sell LocalizedString(@"Sell")
#define BuyInitials LocalizedString(@"BuyInitials")
#define SellInitials LocalizedString(@"SellInitials")
#define OptionalLimited200Characters LocalizedString(@"OptionalLimited200Characters")

//单位
#define HundredMillion LocalizedString(@"HundredMillion")
#define Wan LocalizedString(@"Wan")


//资讯
#define Infomation LocalizedString(@"Infomation")
#define Flash LocalizedString(@"Flash")
#define Share LocalizedString(@"Share")
#define Browse LocalizedString(@"Browse")
#define SourceKey LocalizedString(@"SourceKey")
#define BeeNews LocalizedString(@"BeeNews")
#define FlashShareSlogan LocalizedString(@"FlashShareSlogan")
#define FlashShareDownloadSlogan LocalizedString(@"FlashShareDownloadSlogan")





#endif /* LocalizedKey_h */
